[project]
name = "edin-mls-25-spring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cupy-cuda12x>=13.4.1",
    "numpy>=2.2.4",
    "torch>=2.6.0",
    "triton>=3.2.0",
]
